### ISSUE TITLE
behaviour is not quite identical to what YBD had before....

### ISSUE THREAD

**Issue by devcurmudgeon** [CodethinkLabs/sandboxlib#1]
For master definitions, YBD prior to using sandboxlib (eg https://github.com/devcurmudgeon/ybd/commit/2526c79cdb51ba5ec3f3382719c0327952a0bb81) builds fine. However with sandboxlib  it's less happy...

https://github.com/devcurmudgeon/ybd/issues/45

**Comment by ghost** [comment]
Fixed in 'ybd'. https://github.com/CodethinkLabs/sandboxlib/commit/422325b12d1e8fba90cd92d27968125e00bca40f makes None a valid value for filesystem_writable_paths, which prevents this backtrace (but this doesn't fix the YBD issue in itself, as it should be passing 'all' not 'none' anyway)
