### ISSUE TITLE
n00b user may be unable to install linux-user-chroot

### ISSUE THREAD

**Issue by devcurmudgeon** [CodethinkLabs/sandboxlib#2]
so, for example, if i run ybd on a fresh AWS instance, having installed sandboxlib using pip, i get...

> sh -c 'sh ./create-fhs-dirs "$DESTDIR"'
> line 23: exec: linux-user-chroot: not found

**Comment by ghost** [comment]
How is this best handled?
I was imagining that programs that used sandboxlib could optionally call a function called detect_best_backend() or some such thing that would pick a backend that worked. So if the app was OK with using chroot() and linux-user-chroot wasn't installed, it would use chroot(). If the app explicitly requires linux-user-chroot then there isn't much we can do beyond raise an error...

**Comment by devcurmudgeon** [comment]
seems fair enough. could you rustle up some short guidance on how to install linux-user-chroot, though? i think i've managed it, but on the machine i tested it, i'm still seeing the above error message

**Comment by ghost** [comment]
It's entirely distro-specific. Does AWS have its own distro, or is it Ubuntu or Red Hat or something?

sandboxlib expects `linux-user-chroot` to be in `PATH`, it could certainly give a more helpful error message here.

**Comment by devcurmudgeon** [comment]
On 2015-06-08 13:29, Sam Thursfield wrote:

> It's entirely distro-specific. Does AWS have its own distro, or is it
> Ubuntu or Red Hat or something?
> 
> sandboxlib expects linux-user-chroot to be in PATH, it could 
> certainly
> give a more helpful error message here.

it seems to be their own thing, with yum but not apt.

**Comment by ghost** [comment]
Commit c6fe37a7d60e17d936d8a0f424190bb96fc882bc should give a more helpful error when linux-user-chroot is not found.

**Comment by devcurmudgeon** [comment]
Closing this....
