### ISSUE TITLE
could we shorten three warnings to one, somehow?

### ISSUE THREAD

**Issue by devcurmudgeon** [CodethinkLabs/sandboxlib#8]
this seems overkill, per invocation.

WARNING: Unable to set mounts=isolated in a chroot sandbox, falling back to mounts=undefined
WARNING: Unable to set network=isolated in a chroot sandbox, falling back to network=undefined
WARNING: Unable to set filesystem_writable_paths=['/src/tmp/tmpaQWmFq/stage1-binutils.build', '/src/tmp/tmpaQWmFq/stage1-binutils.inst', '/tmp'] in a chroot sandbox, falling back to filesystem_writable_paths=all

one line per chunk (or even per run - it's not going to change, after all) would be ideal, imo, something like: 

SANDBOXLIB: WARNING: Using chroot - mounts, network and writeable paths are not sandboxed

**Comment by devcurmudgeon** [comment]
strangely I can't find where this text is coming from... i guess chroot itself?

**Comment by ghost** [comment]
I'm a bit confused why warnings are showing up 'per invocation' -- I thought the Python 'warnings' module would only output a warning once per process. That was the main reason I used it here, in fact...

The warnings come from `degrade_config_for_capabilities()` in sandboxlib/chroot.py. We could make `degrate_config_for_capabilities()` collect warning messages and call `warnings.warn()` once at the end , that's probably the easiest way to make it all happen on 1 line

**Comment by devcurmudgeon** [comment]
seems a bit much to have the following every time...

15-07-01 14:18:24 [1/273/273] [stage1-binutils] Running command:
./configure --prefix="$PREFIX" --disable-nls --disable-werror \
  --build=$(sh config.guess) \
  --host=$(sh config.guess) \
  --target=$TARGET_STAGE1 \
  --with-sysroot=/nonexistentdir --with-lib-path="=$PREFIX/lib:=$PREFIX/lib64"

WARNING: Unable to set mounts=isolated in a chroot sandbox, falling back to mounts=undefined
WARNING: Unable to set network=isolated in a chroot sandbox, falling back to network=undefined
WARNING: Unable to set filesystem_writable_paths=['/root/.cache/ybd/tmp/tmpa2uvoo/stage1-binutils.build', '/root/.cache/ybd/tmp/tmpa2uvoo/stage1-binutils.inst', '/tmp'] in a chroot sandbox, falling back to filesystem_writable_paths=all

**Comment by devcurmudgeon** [comment]
so the simplest solution is to set config warn=False, eg in ybd 

```
        config = executor.degrade_config_for_capabilities(config, warn=False)
        ...
        exit_code = executor.run_sandbox_with_redirection(
            argv, stdout=logfile, stderr=sandboxlib.STDOUT,
            env=env, **config)
```

 Thanks @ssssam

**Comment by ghost** [comment]
I had thought that the Python warnings module hid duplicated warnings by default. In fact, default is to show them all, but the _interpreter_ calls `warnings.simplefilter("once")` so that duplicates are hidden. Thus if you test in the interpreter whether duplicate warnings are hidden, they are :) 

I sent https://github.com/devcurmudgeon/ybd/pull/106, which will cause YBD to not print duplicate warning messages.

**Comment by devcurmudgeon** [comment]
Thank you!
